insert into teams (name, league) values
  ('Arsenal', 'Premier League'),
  ('Manchester City', 'Premier League'),
  ('Chelsea', 'Premier League'),
  ('Aston Villa', 'Premier League'),
  ('Brighton', 'Premier League'),
  ('Sunderland', 'Premier League'),
  ('Manchester United', 'Premier League'),
  ('Liverpool', 'Premier League'),
  ('Crystal Palace', 'Premier League'),
  ('Bournemouth', 'Premier League'),
  ('Brentford', 'Premier League'),
  ('Everton', 'Premier League'),
  ('Tottenham', 'Premier League'),
  ('Newcastle', 'Premier League'),
  ('Fulham', 'Premier League'),
  ('Nottingham Forest', 'Premier League'),
  ('West Ham', 'Premier League'),
  ('Leeds United', 'Premier League'),
  ('Burnley', 'Premier League'),
  ('Wolverhampton', 'Premier League'),
  ('Coventry City', 'Championship'),
  ('Middlesbrough', 'Championship'),
  ('Millwall', 'Championship'),
  ('Stoke City', 'Championship'),
  ('Preston North End', 'Championship'),
  ('Bristol City', 'Championship'),
  ('Birmingham City', 'Championship'),
  ('Hull City', 'Championship'),
  ('Ipswich Town', 'Championship'),
  ('Wrexham', 'Championship'),
  ('Derby County', 'Championship'),
  ('West Bromwich Albion', 'Championship'),
  ('Queens Park Rangers', 'Championship'),
  ('Southampton', 'Championship'),
  ('Watford', 'Championship'),
  ('Leicester City', 'Championship'),
  ('Charlton Athletic', 'Championship'),
  ('Blackburn Rovers', 'Championship'),
  ('Sheffield United', 'Championship'),
  ('Oxford United', 'Championship'),
  ('Swansea City', 'Championship'),
  ('Portsmouth', 'Championship'),
  ('Norwich City', 'Championship'),
  ('Sheffield Wednesday', 'Championship'),
  ('AC Milan', 'Serie A'),
  ('Napoli', 'Serie A'),
  ('Inter Milan', 'Serie A'),
  ('AS Roma', 'Serie A'),
  ('Como 1907', 'Serie A'),
  ('Bologna', 'Serie A'),
  ('Juventus', 'Serie A'),
  ('Lazio', 'Serie A'),
  ('Udinese', 'Serie A'),
  ('Sassuolo', 'Serie A'),
  ('Cremonese', 'Serie A'),
  ('Atalanta', 'Serie A'),
  ('Torino', 'Serie A'),
  ('Lecce', 'Serie A'),
  ('Cagliari', 'Serie A'),
  ('Genoa', 'Serie A'),
  ('Parma', 'Serie A'),
  ('Pisa SC', 'Serie A'),
  ('Fiorentina', 'Serie A'),
  ('Hellas Verona', 'Serie A'),
  ('RC Lens', 'Ligue 1'),
  ('Paris Saint-Germain', 'Ligue 1'),
  ('Olympique de Marseille', 'Ligue 1'),
  ('LOSC Lille', 'Ligue 1'),
  ('Stade Rennais', 'Ligue 1'),
  ('Olympique Lyonnais', 'Ligue 1'),
  ('AS Monaco', 'Ligue 1'),
  ('RC Strasbourg Alsace', 'Ligue 1'),
  ('Toulouse FC', 'Ligue 1'),
  ('OGC Nice', 'Ligue 1'),
  ('Stade Brestois', 'Ligue 1'),
  ('Angers SCO', 'Ligue 1'),
  ('Paris FC', 'Ligue 1'),
  ('Le Havre AC', 'Ligue 1'),
  ('FC Lorient', 'Ligue 1'),
  ('FC Nantes', 'Ligue 1'),
  ('FC Metz', 'Ligue 1'),
  ('AJ Auxerre', 'Ligue 1'),
  ('Mjällby', 'Allsvenskan'),
  ('Hammarby', 'Allsvenskan'),
  ('GAIS', 'Allsvenskan'),
  ('IFK Göteborg', 'Allsvenskan'),
  ('Djurgården', 'Allsvenskan'),
  ('Malmö FF', 'Allsvenskan'),
  ('AIK', 'Allsvenskan'),
  ('Elfsborg', 'Allsvenskan'),
  ('Sirius', 'Allsvenskan'),
  ('Häcken', 'Allsvenskan'),
  ('Halmstad', 'Allsvenskan'),
  ('Brommapojkarna', 'Allsvenskan'),
  ('Degerfors', 'Allsvenskan'),
  ('Norrköping', 'Allsvenskan'),
  ('Öster', 'Allsvenskan'),
  ('Värnamo', 'Allsvenskan'),
  ('Västerås SK', 'Superettan'),
  ('Kalmar FF', 'Superettan'),
  ('Örgryte', 'Superettan'),
  ('Oddevold', 'Superettan'),
  ('Falkenberg', 'Superettan'),
  ('Varbergs BoIS', 'Superettan'),
  ('Helsingborg', 'Superettan'),
  ('Brage', 'Superettan'),
  ('BoIS', 'Superettan'),
  ('Sandviken', 'Superettan'),
  ('Sundsvall', 'Superettan'),
  ('Östersund', 'Superettan'),
  ('Utsikten', 'Superettan'),
  ('Örebro', 'Superettan'),
  ('Trelleborg', 'Superettan'),
  ('Umeå FC', 'Superettan'),
  ('Barcelona', 'La Liga'),
  ('Real Madrid', 'La Liga'),
  ('Villarreal', 'La Liga'),
  ('Atlético Madrid', 'La Liga'),
  ('Real Betis', 'La Liga'),
  ('Espanyol', 'La Liga'),
  ('Getafe', 'La Liga'),
  ('Athletic Bilbao', 'La Liga'),
  ('Rayo Vallecano', 'La Liga'),
  ('Real Sociedad', 'La Liga'),
  ('Elche', 'La Liga'),
  ('Celta Vigo', 'La Liga'),
  ('Sevilla', 'La Liga'),
  ('Alavés', 'La Liga'),
  ('Valencia', 'La Liga'),
  ('Real Mallorca', 'La Liga'),
  ('Osasuna', 'La Liga'),
  ('Girona', 'La Liga'),
  ('Levante', 'La Liga'),
  ('Real Oviedo', 'La Liga');
