// <auto-generated />
using System;
using BetBros.Server.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetBros.Server.Migrations
{
    [DbContext(typeof(BetBrosDbContext))]
    partial class BetBrosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BetBros.Server.Models.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Payout")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredictedAwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredictedHomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Prediction")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Profit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScoredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stake")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("BetBros.Server.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BetKind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameWeekId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OverUnderLine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResultEnteredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultEnteredBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BetBros.Server.Models.GameWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameSelectorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameWeeks");
                });

            modelBuilder.Entity("BetBros.Server.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            League = "Premier League",
                            Name = "Arsenal"
                        },
                        new
                        {
                            Id = 2,
                            League = "Premier League",
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 3,
                            League = "Premier League",
                            Name = "Chelsea"
                        },
                        new
                        {
                            Id = 4,
                            League = "Premier League",
                            Name = "Aston Villa"
                        },
                        new
                        {
                            Id = 5,
                            League = "Premier League",
                            Name = "Brighton"
                        },
                        new
                        {
                            Id = 6,
                            League = "Premier League",
                            Name = "Sunderland"
                        },
                        new
                        {
                            Id = 7,
                            League = "Premier League",
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = 8,
                            League = "Premier League",
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 9,
                            League = "Premier League",
                            Name = "Crystal Palace"
                        },
                        new
                        {
                            Id = 10,
                            League = "Premier League",
                            Name = "Bournemouth"
                        },
                        new
                        {
                            Id = 11,
                            League = "Premier League",
                            Name = "Brentford"
                        },
                        new
                        {
                            Id = 12,
                            League = "Premier League",
                            Name = "Everton"
                        },
                        new
                        {
                            Id = 13,
                            League = "Premier League",
                            Name = "Tottenham"
                        },
                        new
                        {
                            Id = 14,
                            League = "Premier League",
                            Name = "Newcastle"
                        },
                        new
                        {
                            Id = 15,
                            League = "Premier League",
                            Name = "Fulham"
                        },
                        new
                        {
                            Id = 16,
                            League = "Premier League",
                            Name = "Nottingham Forest"
                        },
                        new
                        {
                            Id = 17,
                            League = "Premier League",
                            Name = "West Ham"
                        },
                        new
                        {
                            Id = 18,
                            League = "Premier League",
                            Name = "Leeds United"
                        },
                        new
                        {
                            Id = 19,
                            League = "Premier League",
                            Name = "Burnley"
                        },
                        new
                        {
                            Id = 20,
                            League = "Premier League",
                            Name = "Wolverhampton"
                        },
                        new
                        {
                            Id = 21,
                            League = "Championship",
                            Name = "Coventry City"
                        },
                        new
                        {
                            Id = 22,
                            League = "Championship",
                            Name = "Middlesbrough"
                        },
                        new
                        {
                            Id = 23,
                            League = "Championship",
                            Name = "Millwall"
                        },
                        new
                        {
                            Id = 24,
                            League = "Championship",
                            Name = "Stoke City"
                        },
                        new
                        {
                            Id = 25,
                            League = "Championship",
                            Name = "Preston North End"
                        },
                        new
                        {
                            Id = 26,
                            League = "Championship",
                            Name = "Bristol City"
                        },
                        new
                        {
                            Id = 27,
                            League = "Championship",
                            Name = "Birmingham City"
                        },
                        new
                        {
                            Id = 28,
                            League = "Championship",
                            Name = "Hull City"
                        },
                        new
                        {
                            Id = 29,
                            League = "Championship",
                            Name = "Ipswich Town"
                        },
                        new
                        {
                            Id = 30,
                            League = "Championship",
                            Name = "Wrexham"
                        },
                        new
                        {
                            Id = 31,
                            League = "Championship",
                            Name = "Derby County"
                        },
                        new
                        {
                            Id = 32,
                            League = "Championship",
                            Name = "West Bromwich Albion"
                        },
                        new
                        {
                            Id = 33,
                            League = "Championship",
                            Name = "Queens Park Rangers"
                        },
                        new
                        {
                            Id = 34,
                            League = "Championship",
                            Name = "Southampton"
                        },
                        new
                        {
                            Id = 35,
                            League = "Championship",
                            Name = "Watford"
                        },
                        new
                        {
                            Id = 36,
                            League = "Championship",
                            Name = "Leicester City"
                        },
                        new
                        {
                            Id = 37,
                            League = "Championship",
                            Name = "Charlton Athletic"
                        },
                        new
                        {
                            Id = 38,
                            League = "Championship",
                            Name = "Blackburn Rovers"
                        },
                        new
                        {
                            Id = 39,
                            League = "Championship",
                            Name = "Sheffield United"
                        },
                        new
                        {
                            Id = 40,
                            League = "Championship",
                            Name = "Oxford United"
                        },
                        new
                        {
                            Id = 41,
                            League = "Championship",
                            Name = "Swansea City"
                        },
                        new
                        {
                            Id = 42,
                            League = "Championship",
                            Name = "Portsmouth"
                        },
                        new
                        {
                            Id = 43,
                            League = "Championship",
                            Name = "Norwich City"
                        },
                        new
                        {
                            Id = 44,
                            League = "Championship",
                            Name = "Sheffield Wednesday"
                        },
                        new
                        {
                            Id = 45,
                            League = "Serie A",
                            Name = "AC Milan"
                        },
                        new
                        {
                            Id = 46,
                            League = "Serie A",
                            Name = "Napoli"
                        },
                        new
                        {
                            Id = 47,
                            League = "Serie A",
                            Name = "Inter Milan"
                        },
                        new
                        {
                            Id = 48,
                            League = "Serie A",
                            Name = "AS Roma"
                        },
                        new
                        {
                            Id = 49,
                            League = "Serie A",
                            Name = "Como 1907"
                        },
                        new
                        {
                            Id = 50,
                            League = "Serie A",
                            Name = "Bologna"
                        },
                        new
                        {
                            Id = 51,
                            League = "Serie A",
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = 52,
                            League = "Serie A",
                            Name = "Lazio"
                        },
                        new
                        {
                            Id = 53,
                            League = "Serie A",
                            Name = "Udinese"
                        },
                        new
                        {
                            Id = 54,
                            League = "Serie A",
                            Name = "Sassuolo"
                        },
                        new
                        {
                            Id = 55,
                            League = "Serie A",
                            Name = "Cremonese"
                        },
                        new
                        {
                            Id = 56,
                            League = "Serie A",
                            Name = "Atalanta"
                        },
                        new
                        {
                            Id = 57,
                            League = "Serie A",
                            Name = "Torino"
                        },
                        new
                        {
                            Id = 58,
                            League = "Serie A",
                            Name = "Lecce"
                        },
                        new
                        {
                            Id = 59,
                            League = "Serie A",
                            Name = "Cagliari"
                        },
                        new
                        {
                            Id = 60,
                            League = "Serie A",
                            Name = "Genoa"
                        },
                        new
                        {
                            Id = 61,
                            League = "Serie A",
                            Name = "Parma"
                        },
                        new
                        {
                            Id = 62,
                            League = "Serie A",
                            Name = "Pisa SC"
                        },
                        new
                        {
                            Id = 63,
                            League = "Serie A",
                            Name = "Fiorentina"
                        },
                        new
                        {
                            Id = 64,
                            League = "Serie A",
                            Name = "Hellas Verona"
                        },
                        new
                        {
                            Id = 65,
                            League = "Ligue 1",
                            Name = "RC Lens"
                        },
                        new
                        {
                            Id = 66,
                            League = "Ligue 1",
                            Name = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = 67,
                            League = "Ligue 1",
                            Name = "Olympique de Marseille"
                        },
                        new
                        {
                            Id = 68,
                            League = "Ligue 1",
                            Name = "LOSC Lille"
                        },
                        new
                        {
                            Id = 69,
                            League = "Ligue 1",
                            Name = "Stade Rennais"
                        },
                        new
                        {
                            Id = 70,
                            League = "Ligue 1",
                            Name = "Olympique Lyonnais"
                        },
                        new
                        {
                            Id = 71,
                            League = "Ligue 1",
                            Name = "AS Monaco"
                        },
                        new
                        {
                            Id = 72,
                            League = "Ligue 1",
                            Name = "RC Strasbourg Alsace"
                        },
                        new
                        {
                            Id = 73,
                            League = "Ligue 1",
                            Name = "Toulouse FC"
                        },
                        new
                        {
                            Id = 74,
                            League = "Ligue 1",
                            Name = "OGC Nice"
                        },
                        new
                        {
                            Id = 75,
                            League = "Ligue 1",
                            Name = "Stade Brestois"
                        },
                        new
                        {
                            Id = 76,
                            League = "Ligue 1",
                            Name = "Angers SCO"
                        },
                        new
                        {
                            Id = 77,
                            League = "Ligue 1",
                            Name = "Paris FC"
                        },
                        new
                        {
                            Id = 78,
                            League = "Ligue 1",
                            Name = "Le Havre AC"
                        },
                        new
                        {
                            Id = 79,
                            League = "Ligue 1",
                            Name = "FC Lorient"
                        },
                        new
                        {
                            Id = 80,
                            League = "Ligue 1",
                            Name = "FC Nantes"
                        },
                        new
                        {
                            Id = 81,
                            League = "Ligue 1",
                            Name = "FC Metz"
                        },
                        new
                        {
                            Id = 82,
                            League = "Ligue 1",
                            Name = "AJ Auxerre"
                        },
                        new
                        {
                            Id = 83,
                            League = "Allsvenskan",
                            Name = "Mjällby"
                        },
                        new
                        {
                            Id = 84,
                            League = "Allsvenskan",
                            Name = "Hammarby"
                        },
                        new
                        {
                            Id = 85,
                            League = "Allsvenskan",
                            Name = "GAIS"
                        },
                        new
                        {
                            Id = 86,
                            League = "Allsvenskan",
                            Name = "IFK Göteborg"
                        },
                        new
                        {
                            Id = 87,
                            League = "Allsvenskan",
                            Name = "Djurgården"
                        },
                        new
                        {
                            Id = 88,
                            League = "Allsvenskan",
                            Name = "Malmö FF"
                        },
                        new
                        {
                            Id = 89,
                            League = "Allsvenskan",
                            Name = "AIK"
                        },
                        new
                        {
                            Id = 90,
                            League = "Allsvenskan",
                            Name = "Elfsborg"
                        },
                        new
                        {
                            Id = 91,
                            League = "Allsvenskan",
                            Name = "Sirius"
                        },
                        new
                        {
                            Id = 92,
                            League = "Allsvenskan",
                            Name = "Häcken"
                        },
                        new
                        {
                            Id = 93,
                            League = "Allsvenskan",
                            Name = "Halmstad"
                        },
                        new
                        {
                            Id = 94,
                            League = "Allsvenskan",
                            Name = "Brommapojkarna"
                        },
                        new
                        {
                            Id = 95,
                            League = "Allsvenskan",
                            Name = "Degerfors"
                        },
                        new
                        {
                            Id = 96,
                            League = "Allsvenskan",
                            Name = "Norrköping"
                        },
                        new
                        {
                            Id = 97,
                            League = "Allsvenskan",
                            Name = "Öster"
                        },
                        new
                        {
                            Id = 98,
                            League = "Allsvenskan",
                            Name = "Värnamo"
                        },
                        new
                        {
                            Id = 99,
                            League = "Superettan",
                            Name = "Västerås SK"
                        },
                        new
                        {
                            Id = 100,
                            League = "Superettan",
                            Name = "Kalmar FF"
                        },
                        new
                        {
                            Id = 101,
                            League = "Superettan",
                            Name = "Örgryte"
                        },
                        new
                        {
                            Id = 102,
                            League = "Superettan",
                            Name = "Oddevold"
                        },
                        new
                        {
                            Id = 103,
                            League = "Superettan",
                            Name = "Falkenberg"
                        },
                        new
                        {
                            Id = 104,
                            League = "Superettan",
                            Name = "Varbergs BoIS"
                        },
                        new
                        {
                            Id = 105,
                            League = "Superettan",
                            Name = "Helsingborg"
                        },
                        new
                        {
                            Id = 106,
                            League = "Superettan",
                            Name = "Brage"
                        },
                        new
                        {
                            Id = 107,
                            League = "Superettan",
                            Name = "BoIS"
                        },
                        new
                        {
                            Id = 108,
                            League = "Superettan",
                            Name = "Sandviken"
                        },
                        new
                        {
                            Id = 109,
                            League = "Superettan",
                            Name = "Sundsvall"
                        },
                        new
                        {
                            Id = 110,
                            League = "Superettan",
                            Name = "Östersund"
                        },
                        new
                        {
                            Id = 111,
                            League = "Superettan",
                            Name = "Utsikten"
                        },
                        new
                        {
                            Id = 112,
                            League = "Superettan",
                            Name = "Örebro"
                        },
                        new
                        {
                            Id = 113,
                            League = "Superettan",
                            Name = "Trelleborg"
                        },
                        new
                        {
                            Id = 114,
                            League = "Superettan",
                            Name = "Umeå FC"
                        },
                        new
                        {
                            Id = 115,
                            League = "La Liga",
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 116,
                            League = "La Liga",
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 117,
                            League = "La Liga",
                            Name = "Villarreal"
                        },
                        new
                        {
                            Id = 118,
                            League = "La Liga",
                            Name = "Atlético Madrid"
                        },
                        new
                        {
                            Id = 119,
                            League = "La Liga",
                            Name = "Real Betis"
                        },
                        new
                        {
                            Id = 120,
                            League = "La Liga",
                            Name = "Espanyol"
                        },
                        new
                        {
                            Id = 121,
                            League = "La Liga",
                            Name = "Getafe"
                        },
                        new
                        {
                            Id = 122,
                            League = "La Liga",
                            Name = "Athletic Bilbao"
                        },
                        new
                        {
                            Id = 123,
                            League = "La Liga",
                            Name = "Rayo Vallecano"
                        },
                        new
                        {
                            Id = 124,
                            League = "La Liga",
                            Name = "Real Sociedad"
                        },
                        new
                        {
                            Id = 125,
                            League = "La Liga",
                            Name = "Elche"
                        },
                        new
                        {
                            Id = 126,
                            League = "La Liga",
                            Name = "Celta Vigo"
                        },
                        new
                        {
                            Id = 127,
                            League = "La Liga",
                            Name = "Sevilla"
                        },
                        new
                        {
                            Id = 128,
                            League = "La Liga",
                            Name = "Alavés"
                        },
                        new
                        {
                            Id = 129,
                            League = "La Liga",
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 130,
                            League = "La Liga",
                            Name = "Real Mallorca"
                        },
                        new
                        {
                            Id = 131,
                            League = "La Liga",
                            Name = "Osasuna"
                        },
                        new
                        {
                            Id = 132,
                            League = "La Liga",
                            Name = "Girona"
                        },
                        new
                        {
                            Id = 133,
                            League = "La Liga",
                            Name = "Levante"
                        },
                        new
                        {
                            Id = 134,
                            League = "La Liga",
                            Name = "Real Oviedo"
                        });
                });

            modelBuilder.Entity("BetBros.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RotationOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Gärdelöv",
                            IsAdmin = true,
                            PasswordHash = "$2a$11$13y8bUOBLMLcqEXgkB/pPusghKhPV29R3wp1FwvdWgq.Jn5LEh3HO",
                            RotationOrder = 1,
                            Username = "gardelov"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Carlsson",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$V26L1B.sfS3m0zGg.phsaORWlaSL5kf28.siT2WPY1a0grcU7aM9u",
                            RotationOrder = 3,
                            Username = "carlsson"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Danielsson",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$JTQ4wP5h1z8qSBqcuPdb.e10i6mgCgNMftf3WDCZjOaEXk0CfvByK",
                            RotationOrder = 0,
                            Username = "danielsson"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Seeger",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$gHrkkjS8QZ4RAyYlj4w6DOqfWQETdWS1lDqIn2xvSiQpzQNglQuu2",
                            RotationOrder = 2,
                            Username = "seeger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
